name: Spelling & Styles

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Vale Linting
      uses: errata-ai/vale-action@reviewdog
      with:
        fail_on_error: false
        vale_flags: "--no-exit"
        files: README.md