name: Spelling & Styles

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Vale Linting
      uses: vale-cli/vale-action@v2
      with:
        fail_on_error: false
        vale_flags: "--no-exit"
        files: README.md
